
#Unearthed Configs
["generation settings"]
	enable_debug = false
	disable_all = false
	disable_cobble = false
	disable_dirt = false
	disable_ore = false

["general settings"]
	enable_regolith_to_dirt_recipe = false

